version: '3.8'

services:
  app:
    build: .
    container_name: menapln
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
